// SELF LIST STATUS
export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
// *deprecate soon*
export const SET_TABLE_STATE = 'SET_TABLE_STATE';
export const SET_TABLE_SETTINGS = 'SET_TABLE_SETTINGS';

// @STORES*
export const MICROSOFT = 'MICROSOFT';
export const BESTBUY = 'BESTBUY';
export const COSTCO = 'COSTCO';

// BB STATUS
export const GET_BB_ITEMS = 'GET_BB_ITEMS';
export const GET_BB_ITEM_DETAIL = 'GET_BB_ITEM_DETAIL';
export const ADD_BB_ITEM_SPEC = 'GET_BB_ITEM_SPEC';

// CC STATUS
export const GET_CC_ITEMS = 'GET_BB_ITEMS';

// MS STATUS
export const GET_MS_ITEMS = 'GET_MS_ITEMS';
export const GET_MS_ITEM_DETAIL = 'GET_MS_ITEM_DETAIL';
export const ADD_MS_ITEM_SPEC = 'GET_BB_ITEM_SPEC';

// @AUTHENTICATE STATUS
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// @KEEPA: KEEPA STATUS
export const KEEPA_LOADING = 'KEEPA_LOADING';
export const GET_KEEPA_STAT = 'GET_KEEPA_STAT';

// @OPERATION: AMAZON
export const RES_LOADING = 'RES_LOADING';
export const RES_LOADED = 'RES_LOADED';
export const GET_AMZ_PROD_PRICING = 'GET_AMZ_PROD_PRICING';

// @OPERATION: UPLOAD
export const UPLOAD_ASINS_MAPPING = 'UPLOAD_MAPPING';
export const GET_UPC_ASIN_MAPPING = 'GET_UPC_ASIN_MAPPING';
export const ADD_ITEM_SPEC = 'ADD_ITEM_SPEC';
// export const GET_ITEM_SPEC = 'GET_ITEM_SPEC';


